# Generated by Django 5.0.14 on 2026-07-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaConcretaAccion',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Agenda_concreta_accion',
            },
        ),
        migrations.CreateModel(
            name='ContactoNudo',
            fields=[
                ('id_contacto_nudo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'contacto_nudo',
            },
        ),
        migrations.CreateModel(
            name='Nudo',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_nudo', models.AutoField(primary_key=True, serialize=False)),
                ('problema', models.TextField()),
                ('localizacion', models.TextField()),
                ('potencialidades', models.TextField()),
                ('recursos', models.TextField()),
                ('solucion', models.TextField()),
                ('prioridad', models.IntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')])),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('metodo_gestion', models.CharField(choices=[('autogestion', 'Autogestion'), ('cogestion', 'Cogestion'), ('gobierno obedecional', 'Gobierno Obedecional')], max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'Sin iniciar'), (2, 'En pausa'), (3, 'En ejecucion'), (4, 'Resuelto')])),
            ],
            options={
                'db_table': 'Nudo',
            },
        ),
        migrations.CreateModel(
            name='PlanPatria',
            fields=[
                ('id_patria', models.IntegerField(choices=[(1, 'Economica'), (2, 'Independencia, cultura, ciencia y tecnología'), (3, 'Seguridad ciudadana y defensa'), (4, 'Social'), (5, 'Política'), (6, 'Ecosocialismo'), (7, 'Geopolítica')], primary_key=True, serialize=False)),
                ('area', models.TextField()),
            ],
            options={
                'db_table': 'Plan_patria',
            },
        ),
    ]
