# Generated by Django 5.0.14 on 2026-07-12 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda_app', '0001_initial'),
        ('comunidad_app', '0001_initial'),
        ('contactos_app', '0001_initial'),
        ('vocero_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaconcretaaccion',
            name='id_comite',
            field=models.ForeignKey(db_column='id_comite', on_delete=django.db.models.deletion.CASCADE, to='vocero_app.comite'),
        ),
        migrations.AddField(
            model_name='agendaconcretaaccion',
            name='id_comunidad',
            field=models.ForeignKey(db_column='id_comunidad', on_delete=django.db.models.deletion.CASCADE, to='comunidad_app.comunidad'),
        ),
        migrations.AddField(
            model_name='contactonudo',
            name='id_contacto',
            field=models.ForeignKey(db_column='id_contacto', on_delete=django.db.models.deletion.CASCADE, to='contactos_app.contactosinstitucionales'),
        ),
        migrations.AddField(
            model_name='contactonudo',
            name='id_nudo',
            field=models.ForeignKey(db_column='id_nudo', on_delete=django.db.models.deletion.CASCADE, to='agenda_app.nudo'),
        ),
        migrations.AddField(
            model_name='nudo',
            name='id_patria',
            field=models.ForeignKey(db_column='id_patria', on_delete=django.db.models.deletion.CASCADE, to='agenda_app.planpatria'),
        ),
    ]
