# Generated by Django 5.0.14 on 2026-07-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comuna_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_comunidad', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('codigo_registro', models.CharField(max_length=50)),
                ('rif_consejo', models.CharField(max_length=50)),
                ('consejo_comunal', models.CharField(max_length=100)),
                ('comunidad', models.CharField(max_length=50)),
                ('registro_electoral', models.IntegerField()),
                ('codigo_parroquia', models.CharField(max_length=50)),
                ('codigo_comuna', models.ForeignKey(blank=True, db_column='codigo_comuna', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidad', to='comuna_app.comuna')),
            ],
            options={
                'db_table': 'comunidad',
            },
        ),
    ]
