# Generated by Django 5.0.14 on 2026-07-06 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('new_data', models.TextField()),
                ('old_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('INSERT', 'Creacion'), ('UPDATE', 'Modificacion'), ('DELETE', 'Eliminacion')], default='INSERT', max_length=50)),
                ('table_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='historial_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
    ]
