# Generated by Django 5.0.14 on 2026-06-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
