# Generated by Django 5.0.14 on 2026-07-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_comuna', models.CharField(max_length=50)),
                ('nombre_comuna', models.CharField(max_length=100)),
                ('rif_comuna', models.CharField(max_length=50)),
                ('fecha_fundacion', models.DateField()),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
    ]
