# Generated by Django 5.0.14 on 2026-07-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActoresInvolucrados',
            fields=[
                ('id_actor', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'actores_institucionales',
            },
        ),
        migrations.CreateModel(
            name='ContactosInstitucionales',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('rif_contacto', models.CharField(max_length=50)),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=11)),
                ('tipo_contacto', models.CharField(choices=[('Ministerio', 'Ministerio'), ('Empresa Estado', 'Empresa del estado'), ('Fundacion', 'Fundacion'), ('Alcaldia', 'Alcaldia'), ('Gobernacion', 'Gobernacion')], max_length=50)),
            ],
            options={
                'db_table': 'contactos_institucionales',
            },
        ),
    ]
