# Generated by Django 5.0.14 on 2026-07-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actoresinvolucrados',
            name='id_persona',
            field=models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, related_name='actor_involucrado', to='user_app.persona'),
        ),
        migrations.AddField(
            model_name='actoresinvolucrados',
            name='id_contacto',
            field=models.ForeignKey(db_column='id_contacto', on_delete=django.db.models.deletion.CASCADE, related_name='Empleado_institucion', to='contactos_app.contactos_institucionales'),
        ),
    ]
