# Generated by Django 5.0.14 on 2026-07-12 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidad_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id_comite', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comite', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comite',
            },
        ),
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_eleccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_expedicion', models.DateField()),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('codigo_comunidad', models.ForeignKey(db_column='codigo_comunidad', on_delete=django.db.models.deletion.CASCADE, related_name='eleccion', to='comunidad_app.comunidad')),
            ],
            options={
                'db_table': 'eleccion',
            },
        ),
        migrations.CreateModel(
            name='Vocero',
            fields=[
                ('id_vocero', models.AutoField(primary_key=True, serialize=False)),
                ('condicion', models.PositiveSmallIntegerField(choices=[(1, 'Principal'), (2, 'Suplente')], default=1, help_text='indica si el vocero actua como principal o suplente')),
                ('id_comite', models.ForeignKey(db_column='id_comite', on_delete=django.db.models.deletion.CASCADE, to='vocero_app.comite')),
                ('id_eleccion', models.ForeignKey(db_column='id_eleccion', on_delete=django.db.models.deletion.CASCADE, related_name='vocero_electo', to='vocero_app.eleccion')),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, related_name='dato_vocero', to='user_app.persona')),
            ],
            options={
                'db_table': 'vocero',
            },
        ),
    ]
